services:
  YagoSC:
    image: yagoservice:latest
    ports:
      - "13000:13000"
  KeyBertService:
    image: keybertservice:latest
    ports:
      - "5003:5003"
  KeyLLMService:
    image: keyllmservice:latest
    ports:
      - "5002:5002"
  Ojd_service1:
    image: ojddapsservice1:latest
    ports:
      - "5005:5005"

