###
//send request
GET http://localhost:13000

###
//send request
POST http://localhost:13000
Content-Type: application/json

{
  "name": "james",
  "location": "Pisa"
}

###
//REQUEST TO YAGO
//send request upper hierarchy
GET http://localhost:13000/queryUpperHierarchy
Content-Type: application/json

{
 "element": "Red Bull"
}

###

//REQUEST TO YAGO
//send request same level hierarchy
GET http://localhost:13000/querySameLevelHierarchy
Content-Type: application/json

{
  "element": "Coca Cola"
}


###
// Request to keyBertService

GET http://localhost:13001/keywords
Content-Type: application/json

{
  "doc": "Coca-Cola is the most popular and biggest-selling soft drink as well as one of the most recognizable brands in the world. It the only brand that is found in my fridge for my weekend parties"
}

###

GET http://172.17.0.1:5055/keywords
Content-Type: application/json

{
  "doc": "Coca Cola is the most popular and biggest-selling soft drink as well as one of the most recognizable brands in the world. It the only brand that is found in my fridge for my weekend parties. Supervised learning is the machine learning task of learning a function that maps an input to an output based on example input-output pairs. It infers a function from labeled training data consisting of a set of training examples. In supervised learning, each example is a pair consisting of an input object (typically a vector) and a desired output value (also called the supervisory signal). A supervised learning algorithm analyzes the training data and produces an inferred function, which can be used for mapping new examples. An optimal scenario will allow for the algorithm to correctly determine the class labels for unseen instances. This requires the learning algorithm to generalize from the training data to unseen situations in a 'reasonable' way (see inductive bias). "
}


###

// keyLMMService test
GET http://localhost:5080/keywords_only_LMM
Content-Type: application/json

{
  "doc": "Pepsi Cola and Coca Cola, versus Machine Learning Algorithms and Extractors. An optimal scenario will allow for the algorithm to correctly determine the class labels for unseen instances "
}


### keyLMMService BERT+LMM test
GET http://locìalhost:5080/keywords_both
Content-Type: application/json

{
  "doc": "Pepsi Cola and Coca Cola, versus Machine Learning Algorithms and Extractors. An optimal scenario will allow for the algorithm to correctly determine the class labels for unseen instances. Hello, sayonara "
}



###
//test keywords to skill
GET http://localhost:5005/keyword_to_skills
Content-Type: application/json

{
  "keywords": ["Blockchain", "Blockchain consensus mechanism", "working with computers","playing the piano","playing the violin play"]
}


###
//test keywords to skill
GET http://localhost:5005/text_to_skills
Content-Type: application/json

{
  "doc": "Dario was playing the piano"
}


###
###
GET http://localhost:3000/create_did_by_alias?alias="ciao"

###
// test evramo
GET http://localhost:3001/get_own_did

###
GET http://localhost:3001/get_did_doc?did=did:ethr:goerli:0x034e4ecfb60a1a922c027c356480eab896c21f9eb95feabdb6e8408492c81c3f84
Content-Type: application/json

###
GET http://localhost:3001/get_verifiable_credential?hash_cred=QmddTNfSuDoNDytXvagAad8bERKe2iTSZkucApuU1VgAXj


###
GET http://localhost:3001/issue_verifiable_credential?issuer=did:ethr:sepolia:0x0242ccfbd55f4e1816ce6aec889161764227c48f2234feac158ecacd9cb94836a1&holder=did:ethr:sepolia:0x0242ccfbd55f4e1816ce6aec889161764227c48f2234feac158ecacd9cb94836a1&attributes={"hi":"hello"}&store=true
Content-Type: application/json



###
GET http://localhost:3001/list_verifiable_credentials

###
GET http://localhost:3001/get_qr_code?hash=QmXvBCqkEFw6Tc14ct8TRReAZ7UkruJzFwPaSi8RFKj7rR

###
GET http://localhost:3001/verify


### Test extract API ###

# POST request to /api/extract
POST http://localhost:4200/api/extract
Content-Type: application/json

{
  "document": "The study explores the impact of climate change on coral reef ecosystems."
}


### Test Helia API ###

# POST request to /publish
POST http://localhost:4201/publish
Content-Type: application/json

{
  "identityId": "Cal",
  "toStore": "hello12"
}


###
# GET read from cit
GET http://localhost:4201/read_cid?requestedCid=/bafkreifhe7tyc6aspx6oroqultlew6jjumh2ykgh5ajua5q672q4lgxobe


###

# POST request to /publish
POST http://localhost:4201/upload
Content-Type: application/json

{
  "text": "Calogerp",
  "identityId" : "Cal"
}

###

# POST request to /publish
GET http://localhost:4201/fetch?gotCID=bafkreiahnvzbzyvwoizrxprk7574gkgdg5uin72j2vt26knmiizswbstca








