ner_model_path: "outputs/models/ner_model/20230808/"
taxonomy_name: "esco"
taxonomy_path: "outputs/data/skill_ner_mapping/esco_data_formatted1.csv"
clean_job_ads: True
min_multiskill_length: 75
#taxonomy_embedding_file_name: "outputs/data/skill_ner_mapping/esco_embeddings1.json" to remove, because based on old version
prev_skill_matches_file_name: "outputs/data/skill_ner_mapping/ojo_esco_lookup_sample1.json"
hard_labelled_skills_file_name: "outputs/data/skill_ner_mapping/hardcoded_ojo_esco_lookup1.json"
hier_name_mapper_file_name: "outputs/data/skill_ner_mapping/esco_hier_mapper1.json"
num_hier_levels: 4
skill_type_dict:
  {
    "skill_types": ["preferredLabel", "altLabels"],
    "hier_types": ["level_2", "level_3"],
  }
match_thresholds_dict:
  {
    "skill_match_thresh": 0.7,
    "top_tax_skills": { 1: 0.5, 2: 0.5, 3: 0.5 },
    "max_share": { 1: 0, 2: 0.2, 3: 0.2 },
  }
skill_name_col: "description"
skill_id_col: "id"
skill_hier_info_col: "hierarchy_levels"
skill_type_col: "type"
